VAR1: CONTENIDO DE VALOR1
My.VAR2: 100
var4:
 try1: 200
 try2: 400
javaDir: ${java.home:"NO JAVA"}
url: localhost
password: qwerty
logging.config: src\main\resources\logback-spring.xml
spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 datasource:
  url: jdbc:h2:file:~/test09
  driverClassName: org.h2.Driver
  username: sa
  password:
 jpa:
  show-sql: true
  properties:
   hiberante:
    format: true
  hibernate:
   ddl-auto: create-drop
hibernate:
 dialect: org.hibernate.dialect.HSQLDialect
