spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 datasource:
  url: jdbc:h2:file:~/test09
  driverClassName: org.h2.Driver
  username: sa
  password:
 jpa:
  show-sql: true
  properties:
   hiberante:
    format: true
  hibernate:
   ddl-auto: create-drop
hibernate:
 dialect: org.hibernate.dialect.HSQLDialect
